### PR TITLE
Launch AspNet integration from profiler instead of IIS config

### PR DESCRIPTION
**Pull request by zacharycmontoya**
- Remove Datadog.Trace.AspNet.TracingHttpModule from applicationHost.xdt
- TODO: Update .NET Tracer version with latest version that contains the change

### CODE REVIEW

**Comment by lucaspimentel** [comment]
With this change, we can allow users to install the extension on a running app. Should we make that change in this PR?

**Comment by zacharycmontoya** [comment]
> With this change, we can allow users to install the extension on a running app. Should we make that change in this PR?

Good point, yes I think we should do that in the same PR.  @colin-higgins do you agree / disagree?

**Comment by colin-higgins** [comment]
We will need to make sure support knows this and it's heavily bolded in all the places.
Users will *definitely* install/upgrade and never stop the app.

**Comment by zacharycmontoya** [comment]
> With this change, we can allow users to install the extension on a running app. Should we make that change in this PR?

@lucaspimentel @colin-higgins I'm thinking of merging this and then removing install scripts in a separate PR, especially since we've done some validation already. Is that fine with you?

**Comment by colin-higgins** [comment]
To be clear, we should not remove the install scripts, only the validation on w3wp being stopped from the install scripts, but I agree otherwise.

**Review by colin-higgins — APPROVED** [review]

**Review by lucaspimentel — APPROVED** [review]

**Comment by zacharycmontoya** [comment]
> To be clear, we should not remove the install scripts, only the validation on w3wp being stopped from the install scripts, but I agree otherwise.

Yep, understood

**Pull request merged**
